<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE student [
    <!ELEMENT student (name?,age*,sex)>
    <!ELEMENT name (#PCDATA)>
    <!ELEMENT age (#PCDATA)>
    <!ELEMENT sex1 (#PCDATA)>
]>
<student>
	<name>zhangsan</name>
	<age>20</age>
	<age>20</age>
	<sex>female</sex>
</student>
